---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-bot
  namespace: infrastructure-docs

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inventory-bot-reader
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - pods
      - services
    verbs:
      - get
      - list
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs:
      - get
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: inventory-bot-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: inventory-bot-reader
subjects:
  - kind: ServiceAccount
    name: inventory-bot
    namespace: infrastructure-docs
