---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: auto-inventory-bot
  namespace: infrastructure-docs
  labels:
    app: inventory-bot
spec:
  schedule: "0 2 * * *"  # Daily at 2 AM UTC
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: inventory-bot
        spec:
          serviceAccountName: inventory-bot
          restartPolicy: OnFailure

          # CRITICAL: Force execution on prod3 to save resources
          nodeSelector:
            kubernetes.io/hostname: prod3

          initContainers:
            - name: git-clone
              image: alpine/git:latest
              command:
                - sh
                - -c
                - |
                  echo "🔄 Cloning repository..."
                  git clone http://${GIT_USERNAME}:${GIT_PASSWORD}@${GIT_REPO_URL} /workspace
                  echo "✅ Repository cloned successfully"
                  ls -la /workspace
              env:
                - name: GIT_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: git-credentials
                      key: username
                - name: GIT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: git-credentials
                      key: password
                - name: GIT_REPO_URL
                  valueFrom:
                    secretKeyRef:
                      name: git-credentials
                      key: repo_url
              volumeMounts:
                - name: workspace
                  mountPath: /workspace

          containers:
            - name: inventory-bot
              image: 172.16.16.161:30551/inventory-bot:latest
              imagePullPolicy: Always
              command: ["/bin/bash", "/scripts/run.sh"]
              env:
                - name: OUTPUT_DIR
                  value: "/workspace/docs"
                - name: GIT_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: git-credentials
                      key: username
                - name: GIT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: git-credentials
                      key: password
              volumeMounts:
                - name: workspace
                  mountPath: /workspace
                - name: git-wrapper
                  mountPath: /scripts
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "100m"
                limits:
                  memory: "256Mi"
                  cpu: "200m"

          volumes:
            - name: workspace
              emptyDir: {}
            - name: git-wrapper
              configMap:
                name: git-wrapper
                defaultMode: 0755
